MyBlog/Blog/urls.py
"""Blog URL 结构

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.11/topics/http/urls/
例子:
功能视图
    1. 添加一个导入:  from my_app import views
    2. 添加一个URL到 urlpatterns:  url(r'^$', views.home, name='home')
基于类的视图
    1. 添加一个导入:  from other_app.views import Home
    2. 添加一个URL到 urlpatterns:  url(r'^$', Home.as_view(), name='home')
包含其他的 URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. 添加一个URL到 urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('blogs.urls', namespace='blogs')),
]

MyBlog/blogs/urls.py
# -*- coding: utf-8 -*-
"""定义blogs的URL模式"""
from django.conf.urls import url

from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    
    # 浏览博客
    url(r'^show_blog/$', views.show_blog, name='show_blog'),
    
    # 添加新博客
    url(r'^new_blog/$', views.new_blog, name='new_blog'),
    
    # 修改博客
    url(r'^edit_blog/(?P<blog_id>\d+)/$', views.edit_blog, name='edit_blog'),
]

MyBlog/users/urls.py
#!/usr/bin/env python3
# -*- coding:utf-8 -*-
"""为应用程序USERS配置URL模式"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # 登录页面
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
    
    # 注销
    url(r'^logout/$', views.logout_view, name='logout'),
    
    # 注册
    url(r'^register/$', views.register, name='register'),
]

MyBlog/blogs/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

# 模型放置区

class BlogPost(models.Model):
    """个人博客向数据库储存的内容"""
    # 博客标题
    title = models.CharField(max_length=200)
    # 博客内容
    text = models.TextField()
    # 发布时间
    date_added = models.DateTimeField(auto_now_add=True)
    # 所属用户
    owner = models.ForeignKey(User)
    
    class Meta:
        verbose_name_plural = '个人博客'
    
    def __str__(self):
        """返回模型的字符串表示"""
        if len(self.title) >= 50:
            return self.title[:50] + '...'
        else:
            return self.title

MyBlog/users/models.py
from django.db import models

# Create your models here.

MyBlog/blogs/forms.py
from django import forms

from .models import BlogPost

class BlogForm(forms.ModelForm):
    class Meta:
        model = BlogPost
        fields = ['title', 'text']
        labels = {'title': '', 'text': ''}

MyBlog/blogs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import BlogPost
from .forms import BlogForm

# Create your views here.
def check_blog_owner(blog_owner, user):
    if blog_owner != user:
        raise Http404

def index(request):
    """网站首页"""
    return render(request, 'blogs/index.html')

def show_blog(request):
    """展示所有的博客,并分页"""
    blogs = BlogPost.objects.order_by('-date_added')
    paginator = Paginator(blogs, 5)
    
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        # 如果页面不是整数，请发送第一页。
        contacts = paginator.page(1)
    except EmptyPage:
        # 如果页面超出范围（例如9999），提交最后一页的结果。
        contacts = paginator.page(paginator.num_pages)
        
    context = {'blogs': blogs, 'contacts': contacts,
               'page_range': paginator.page_range}
    return render(request, 'blogs/show_blog.html', context)

@login_required
def new_blog(request):
    """添加新博客"""
    
    # 判断是否有数据提交
    if request.method != 'POST':
        # 未提交数据 创建一个新表单
        form = BlogForm()
    else:
        # Post提交了数据 对数据进行处理
        form = BlogForm(request.POST)
        if form.is_valid():
            new_blog = form.save(commit=False)
            new_blog.owner = request.user
            new_blog.save()
            return HttpResponseRedirect(reverse('blogs:index'))
    
    context = {'form': form}
    return render(request, 'blogs/new_blog.html', context)
    
@login_required
def edit_blog(request, blog_id):
    """编辑博客"""
    blog = BlogPost.objects.get(id=blog_id)
    check_blog_owner(blog.owner, request.user)
    
    if request.method != 'POST':
        # 改动前 把数据放入表单内
        form = BlogForm(instance=blog)
    else:
        # Post提交了数据 对数据进行处理
        form = BlogForm(instance=blog, data=request.POST)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect(reverse('blogs:index'))
    
    context = {'blog': blog, 'form': form}
    return render(request, 'blogs/edit_blog.html', context)

MyBlog/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

# 在这创建你的视图

def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('blogs:index'))

def register(request):
    """注册"""
    if request.method != 'POST':
        # 显示空的注册信息
        form = UserCreationForm()
    
    else:
        # 处理填写好的订单
        form = UserCreationForm(request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录
            authenticated_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            # 验证无误后登录
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))
    
    context = {'form': form}
    return render(request, 'users/register.html', context)

MyBlog/blogs/templates/blogs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <meta http-equiv="Content-Language" content="zh-CN" />
  <meta name="author" content="Ggzzhh" />
  <meta name="description" content="学习日志" />
  <meta name="keywords" content="python html css javascript ajax java java"/>
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <title>个人微博客</title>
  <style>
    body {
      padding: 60px;
    }
  </style>
</head>  
<body>
  <nav class="navbar navbar-inverse navbar-fixed-top">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed"
                data-toggle="collapse" data-target="#navbar-1"
                aria-expanded="false">
        </button>

        <a href="{% url 'blogs:index' %}" class="navbar-brand">
          <span class="glyphicon glyphicon-home" aria-hidden="true"></span>
        </a>
      </div>


      <div class="collapse navbar-collapse" id="navbar-1">
        <ul class="nav navbar-nav">
          <li>
            <a href="{% url 'blogs:show_blog' %}">浏览博客</a>
          </li>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          {% if user.is_authenticated %}
          <li><a href="#">你好, {{ user.username }}</a></li>
          <li><a href="{% url 'users:logout' %}">注销</a></li>
          {% else %}
          <li><a href="{% url 'users:register' %}">注册</a></li>
          <li><a href="{% url 'users:login' %}">登录</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>

  <div class="container-fluid">
    <div class="page-header">
      {% block header %}
      {% endblock header %}
    </div>
    <div>
      {% block content %}
      {% endblock content %}
    </div>

  </div>

</body>  
</html>  

MyBlog/blogs/templates/blogs/edit_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header%}
<div class="jumbotron" >
    <h1>编辑博客</h1>
</div>
{% endblock header%}

{% block content %}

    <form action="{% url 'blogs:edit_blog' blog.id %}" method="post" class="form">
      {% csrf_token %}

        <h3>标题</h3>
        {% bootstrap_field form.title %}
        <h3>内容</h3>
        {% bootstrap_field form.text %}

      {% buttons %}
       <button name="submit" class="btn btn-primary">提交</button>
      {% endbuttons %}
    </form>
{% endblock content %}

MyBlog/blogs/templates/blogs/index.html
{% extends "blogs/base.html" %}

{% block header%}
<div class="jumbotron">
    <h1 class="text-center">欢迎来到我的博客</h1>
    <br>
    <p>
        这个博客记录了本人学习python所获得的大部分知识,<br>
        也是我学习python后所做的第一个网站，<br>
        你也可以使用这个人博客来记录一些你的信息。<br>
    </p>
    <br>
    <p>
        <a href="{% url 'blogs:show_blog' %}" class="btn btn-primary btn-lg">
            点击这里开始浏览这里所有的博客
        </a>
    </p>

</div>
{% endblock header%}

{% block content %}

{% endblock content %}

MyBlog/blogs/templates/blogs/new_blog.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header%}
<div class="jumbotron" >
    <h1>编写新博客</h1>
</div>
{% endblock header%}

{% block content %}

    <form action="{% url 'blogs:new_blog' %}" method="post" class="form">
      {% csrf_token %}

        <h3>标题</h3>
        {% bootstrap_field form.title placeholder='在这里写标题'%}
        <h3>内容</h3>
        {% bootstrap_field form.text placeholder='在这里写内容'%}

      {% buttons %}
       <button name="submit" class="btn btn-primary">提交</button>
      {% endbuttons %}
    </form>
{% endblock content %}

MyBlog/blogs/templates/blogs/show_blog.html
{% extends "blogs/base.html" %}

{% block header%}
<div class="jumbotron" >
    <h1>博客</h1>
    <p class="text-right">
        <a href="{% url 'blogs:new_blog' %}">添加新博客</a>
    </p>
</div>
{% endblock header%}


{% block content %}
<!--开始循环输出所有博客-->
{% for blog in contacts %}
<div class="panel panel-default">

    <div class="panel-body">
        <h4>
            <p class="alert alert-success">{{blog.title}}</p>
        </h4>
        <div class="jumbotron">
                {{ blog.text }}
        </div>
    </div>

    <div class="panel-footer">
        <div class="row">
            <div class="col-md-3 text-left ">
                {% if blog.owner == user %}
                <a href="{% url 'blogs:edit_blog' blog.id %}" >
                    <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
                    编辑
                </a>
                {% endif %}
            </div>
            <div class="col-md-9 text-right">
                作者：{{ blog.owner }}
                &nbsp;&nbsp;&nbsp;
                {{ blog.date_added|date:'Y年 M d日 H:i' }}
            </div>
        </div>
    </div>
</div>
{% endfor %}

<nav aria-label="Page navigation">
  <ul class="pagination">
    {% if contacts.has_previous %}
    <li>
      <a href="?page={{ contacts.previous_page_number }}" aria-label="Previous">
        <span aria-hidden="true">&laquo;</span>
      </a>
    </li>
    {% endif %}

    {% for page in page_range %}
    <li><a href="?page={{ page }}">{{ page }}</a></li>

    {% endfor %}

    {% if contacts.has_next %}
    <li>
      <a href="?page={{ contacts.next_page_number }}" aria-label="Next">
        <span aria-hidden="true">&raquo;</span>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>

{% endblock content %}

MyBlog/users/templates/users/login.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <div class="jumbotron text-center" style="font-color:#a5f6c4; ">
    <h1>登录</h1>
  </div>
{% endblock header %}

{% block content %}
  {% if form.errors %}
  <p>你的用户名跟密码不匹配，请重试</p>
  {% endif %}

  <form method="post" action="{% url 'users:login' %}" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}

  <button name="submit" class="btn btn-primary">登录</button>
  <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
  </form>
{% endblock content %}

MyBlog/users/templates/users/register.html
{% extends "blogs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <div class="jumbotron text-center" style="font-color:#a5f6c4; ">
    <h1>注册</h1>
  </div>
{% endblock header %}

{% block content %}
  {% if form.errors %}
  <p>你的用户名跟密码不匹配，请重试</p>
  {% endif %}

  <form method="post" action="{% url 'users:register' %}" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}

  <button name="submit" class="btn btn-primary">注册</button>
  <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
  </form>
{% endblock content %}