www/learning_log/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'', include('learning_logs.urls', namespace='learning_logs')),
]

www/learning_logs/urls.py
# -*- coding: utf-8 -*-
"""定义learning_logs的URL模式"""
from django.conf.urls import url

from . import views

urlpatterns = [
    # 主页
    url(r'^$', views.index, name='index'),
    
    # 显示所有主题的网页
    url(r'^topics/$', views.topics, name='topics'),
    
    # 特定主题的详细页面
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    
    # 用于添加新主题的网页
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    
    # 用于添加新条目的页面
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    
    # 用于编辑条目的页面
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, 
        name='edit_entry')
]

www/users/urls.py
# -*- coding: utf-8 -*-
"""为应用程序users定义URL模式"""

from django.conf.urls import url
from django.contrib.auth.views import login

from . import views

urlpatterns = [
    # 登录页面
    url(r'^login/$', login, {'template_name': 'users/login.html'},
        name='login'),
        
    # 注销
    url(r'^logout/$', views.logout_view, name='logout'),
    
    # 注册页面
    url(r'^register/$', views.register, name='register'),
]

www/learning_logs/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.contrib.auth.models import User

# 在这里创建模型
class Topic(models.Model):
    """用户要学习的主题"""
    text = models.CharField(max_length=200) # 创建一个最大长度为200的文本
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)
    
    class Meta:
        verbose_name = "主题"
        verbose_name_plural = "主题"
        #app_label = u"主题"
        #pass
    
    def __str__(self):
        """return text"""
        return self.text
        
class Entry(models.Model):
    """学到的有关某个主题的具体知识"""
    # 学到的有关某个主题的具体知识
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        verbose_name_plural = '主题内容'
        
    def __str__(self):
        """return text"""
        if len(self.text) > 50:
            return self.text[:50] + "..."
        else:
            return self.text

www/learning_logs/forms.py
# -*- coding: utf-8 -*-
from django import forms

from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
        
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

www/learning_logs/views.py
# -*- coding: utf-8 -*-
from django.shortcuts import render
# HttpResponseRedirect 是重定向 Http404的作用是一个错误页面
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
# @login_required 在运行代码前检查用户是否已登录 没登录就转到登录页面
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

def check_topic_owner(topic_owner, user):
    """验证请求主题的用户是当前用户"""
    if topic_owner != user:
        raise Http404

# 在这创建你的视图
def index(request):
    """learning_log index"""
    return render(request, 'learning_logs/index.html')
    
@login_required
def topics(request):
    """用户主题"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)
    
@login_required
def topic(request, topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    # 确认请求的主题属于当前用户
    check_topic_owner(topic.owner, request.user)
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'learning_logs/topic.html', context)

@login_required
def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据：创建一个新表单
        form = TopicForm()
    else:
        # POST提交了数据，对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))
            
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    check_topic_owner(topic.owner, request.user)
    
    if request.method != 'POST':
        # 如果没有提交数据，就创建一个新表单
        form = EntryForm()
    else:
        # POST提交了数据，对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                                args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)

@login_required
def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    check_topic_owner(topic.owner, request.user)
    
    if request.method != 'POST':
        # 初次请求, 使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交了数据，对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',
                                        args=[topic.id]))
    context = {'entry': entry, 'topic':topic, 'form':form}
    return render(request, 'learning_logs/edit_entry.html', context)

www/users/views.py
from django.shortcuts import render

from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def logout_view(request):
    """注销用户"""
    logout(request)
    return HttpResponseRedirect(reverse('learning_logs:index'))
    
def register(request):
    """注册新用户"""
    if request.method != 'POST':
        # 显示空的注册表单
        form = UserCreationForm()
    else:
        # 处理填写好的表单
        form = UserCreationForm(data=request.POST)
        
        if form.is_valid():
            new_user = form.save()
            # 让用户自动登录，再重定向到主页
            # 进行身份验证
            authenticate_user = authenticate(username=new_user.username,
                password=request.POST['password1'])
            # 让用户自动登录
            login(request, authenticate_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    
    context = {'form': form}
    return render(request, 'users/register.html', context)

www/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="zh-CN" >
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta http-equiv="Content-Language" content="zh-CN" />
    <meta name="author" content="Ggzzhh" />
    <meta name="description" content="学习日志" />
    <meta name="keywords" content="python html css javascript ajax java java "/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />

    <title>学习日志</title>
    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>
<body>
<!-- 静态导航 -->
<nav class="navbar navbar-default navbar-static-top">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar">
            </button>
            <a class="navbar-brand" href="{% url 'learning_logs:index' %}">
                学习日志</a>
        </div>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'learning_logs:topics' %}">主题</a></li>
            </ul>

            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                <li><a>你好，{{ user.username }}</a></li>
                <li><a href="{% url 'users:logout' %}">注销</a></li>
                {% else %}
                <li><a href="{% url 'users:login' %}">登录</a></li>
                <li><a href="{% url 'users:register' %}">注册</a></li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <div class="page-header">
        {% block header %}{% endblock header %}
    </div>
    <div>
        {% block content %}{% endblock content %}
    </div>
</div> <!-- /container -->

</body>  
</html>  

www/learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>主题<a href="{% url 'learning_logs:topic' topic.id %}">
    {{ topic }}</a><h2>
{% endblock header %}

{% block content %}

  <h3>编辑条目:</h3>
  <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post'
        class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name='submit' class="btn btn-info">保存编辑</button>
    {% endbuttons %}
  </form>
  
{% endblock content %}

www/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <div class="jumbotron">
        <h1>跟踪你的学习进度</h1>
    </div>
{% endblock header %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">注册一个账户</a>
        开始创建你自己的学习日志，列出你所学习的一切主题！
    </h2>
    <h2>
        不管你获得了主题中的任何知识，都可以创建一个条目出来，说说看你都学到了什么！
    </h2>
{% endblock content %}
  

www/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>主题<a href="{% url 'learning_logs:topic' topic.id %}">
    {{ topic }}</a><h2>
{% endblock header %}

{% block content %}

  <h3>添加新条目</h3>
  <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post'
        class="form">
    {% csrf_token %}
    {% bootstrap_filed form.title %}
    {% buttons %}
    <button name='submit' class="btn btn-info">提交</button>
    {% endbuttons %}
  </form>
  
{% endblock content %}

www/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>创建一个新主题</h2>
{% endblock header %}

{% block content %}
  
  <form action="{% url 'learning_logs:new_topic' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">添加主题</button>
    {% endbuttons %}
  </form>
  
{% endblock content %}

www/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block hearder %}
   <h2> 主题: {{ topic }} </h2>
{% endblock hearder %}

{% block content %}
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">添加一个新条目</a>
    </p>
    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
            <h3>
                {{ entry.date_added|date:'M d, Y H:i' }}
                <small>
                    <div class="text-right">
                        <a href="{% url 'learning_logs:edit_entry' entry.id %}">
                        编辑
                        </a>
                    </div>
                </small>
            </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div><!-- panel -->
    {% empty %}
        <h2>现在这个主题没有条目</h2>
    {% endfor %}
    
{% endblock content %}

www/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
    <h1>主题</h1>
{% endblock header %}

{% block content %}

    <ul>
      {% for topic in topics %}
        <li>
          <h3>
            <a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a>
          </h3>
        </li>
      {% empty %}
        <li>现在没有主题</li>
      {% endfor %}
    </ul>
    
    <h3><a href="{% url 'learning_logs:new_topic' %}">添加主题</a></h3>
    
{% endblock content %}

www/users/templates/users/login.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>登录你的账户</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:login' %}" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
    <button name="submit" class="btn btn-primary">登录</button>
  {% endbuttons %}

    <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
  </form>
  
{% endblock content %}

www/users/templates/users/register.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>注册新用户</h2>
{% endblock header %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}" class="form">
  {% csrf_token %}
  {% bootstrap_form form %}

  {% buttons %}
  <button name="submit" class="btn btn-info">注册</button>
  {% endbuttons %}
  <input type="hidden" name="next" value="{% url 'learning_logs:index' %}">
  </form>

{% endblock content %}